# Generated by Django 4.0 on 2022-05-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipie', '0007_alter_ingredient_unit_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PortionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xs', models.PositiveIntegerField(default=0)),
                ('sm', models.PositiveIntegerField(default=0)),
                ('md', models.PositiveIntegerField(default=0)),
                ('lg', models.PositiveIntegerField(default=0)),
                ('xl', models.PositiveIntegerField(default=0)),
                ('VEGITARIAN', models.PositiveIntegerField(default=0)),
                ('VEGAN', models.PositiveIntegerField(default=0)),
                ('DAIRY', models.PositiveIntegerField(default=0)),
                ('MP_ALLERGIES', models.PositiveIntegerField(default=0)),
                ('GLUTEN', models.PositiveIntegerField(default=0)),
                ('LEGUMINOUS', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartRecipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cart')),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.recipie')),
            ],
        ),
    ]
