# Generated by Django 4.0 on 2022-05-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0007_alter_ingredient_unit_and_more'),
        ('core', '0003_remove_cartrecipie_cart_cartrecipie_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.recipie')),
            ],
        ),
        migrations.RemoveField(
            model_name='portiongroup',
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartRecipie',
        ),
        migrations.AddField(
            model_name='portiongroup',
            name='cart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='core.cartitem'),
        ),
    ]
