# Generated by Django 4.0 on 2022-05-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartitem_remove_portiongroup_cart_delete_cartrecipie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portiongroup',
            name='xl',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
