# Generated by Django 4.0 on 2022-05-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_portiongroup_dairy_alter_portiongroup_gluten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portiongroup',
            name='xs',
            field=models.IntegerField(default=0),
        ),
    ]
