# Generated by Django 4.0 on 2022-05-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_portiongroup_xs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portiongroup',
            name='xs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
