# Generated by Django 4.0 on 2022-05-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_portiongroup_xs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portiongroup',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portion_group', to='core.cartitem'),
        ),
    ]
