# Generated by Django 4.0 on 2022-05-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_portiongroup_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portiongroup',
            name='cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='core.cartitem'),
        ),
    ]
