# Generated by Django 4.0 on 2021-12-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descrtiption', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('image_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_amount', models.FloatField()),
                ('unit', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('hg', 'hg'), ('ml', 'ml'), ('cl', 'cl'), ('dl', 'dl'), ('l', 'l'), ('st', 'st'), ('tsk', 'tsk'), ('msk', 'msk')], max_length=3, null=True)),
                ('category', models.CharField(blank=True, choices=[('V', 'VEGETABLE'), ('F', 'FRUIT'), ('R', 'REFRIGERATED'), ('S', 'SPICE'), ('DG', 'DRY_GOOD')], max_length=3, null=True)),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.recipie')),
            ],
        ),
    ]
