# Generated by Django 4.0 on 2021-12-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, choices=[('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('REFRIGERATED', 'Refrigerated'), ('SPICE', 'Spice'), ('DRY_GOOD', 'Dry good')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipie.recipie'),
        ),
    ]
