# Generated by Django 4.0 on 2022-01-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0004_rename_descrtiption_recipie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipieIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipie',
        ),
        migrations.AddField(
            model_name='recipie',
            name='ingredients',
            field=models.ManyToManyField(through='recipie.RecipieIngredient', to='recipie.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipieingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.ingredient'),
        ),
        migrations.AddField(
            model_name='recipieingredient',
            name='recipie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.recipie'),
        ),
    ]
