# Generated by Django 4.0 on 2022-01-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0005_recipieingredient_remove_ingredient_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipieingredient',
            name='replaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipieingredient',
            name='replaces_reason',
            field=models.CharField(blank=True, choices=[('VEGITARIAN', 'Vegitarian'), ('VEGAN', 'Vegan'), ('DAIRY', 'Dairy'), ('GLUTEN', 'Gluten'), ('LEGUMINOUS', 'Leguminous')], max_length=255, null=True),
        ),
    ]
